spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/excel-test
    username: postgres
    password: asdf1020@@
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      platform: postgresql
      mode: always


